import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fpl_wager/app/theme/app_theme.dart';
import 'package:fpl_wager/core/ui/app_header.dart';
import 'package:fpl_wager/core/ui/app_widgets.dart';
import 'package:fpl_wager/features/challenges/domain/challenge.dart';
import 'package:fpl_wager/features/challenges/presentation/challenges_controller.dart';

final challengeStakeProvider=NotifierProvider<ChallengeStakeController,int>(ChallengeStakeController.new);
class ChallengeStakeController extends Notifier<int>{@override int build()=>100000;void select(int value)=>state=value;}

class ChallengesScreen extends ConsumerStatefulWidget{const ChallengesScreen({super.key});@override ConsumerState<ChallengesScreen> createState()=>_ChallengesScreenState();}
class _ChallengesScreenState extends ConsumerState<ChallengesScreen>{final _form=GlobalKey<FormState>();final _opponent=TextEditingController();@override void dispose(){_opponent.dispose();super.dispose();}
@override Widget build(BuildContext context){final challenges=ref.watch(challengesProvider);final action=ref.watch(challengeActionProvider);final stake=ref.watch(challengeStakeProvider);ref.listen(challengeActionProvider,(_,next){if(next.hasError)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(next.error.toString())));});return Scaffold(appBar:const AppHeader(title:'Head to head'),body:RefreshIndicator(onRefresh:()async{ref.invalidate(challengesProvider);await ref.read(challengesProvider.future);},child:ListView(padding:const EdgeInsets.fromLTRB(AppSpacing.md,8,AppSpacing.md,120),children:[Text('Challenge any verified FPL manager. Winner takes the pot.',style:TextStyle(color:Theme.of(context).colorScheme.onSurfaceVariant)),const SizedBox(height:18),GradientPanel(child:Form(key:_form,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(Icons.compare_arrows_rounded,color:Theme.of(context).colorScheme.secondary),const SizedBox(width:10),Text('New challenge',style:Theme.of(context).textTheme.titleLarge)]),const SizedBox(height:18),TextFormField(controller:_opponent,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Opponent FPL Team ID',prefixIcon:Icon(Icons.tag_rounded)),validator:(value)=>int.tryParse(value??'')==null?'Enter a valid numeric team ID':null),const SizedBox(height:16),Text('Stake',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:8),Wrap(spacing:8,children:[50000,100000,200000,500000].map((value)=>ChoiceChip(label:Text(money(value)),selected:stake==value,onSelected:(_)=>ref.read(challengeStakeProvider.notifier).select(value))).toList()),const SizedBox(height:18),FilledButton(onPressed:action.isLoading?null:()async{if(!(_form.currentState?.validate()??false))return;final ok=await ref.read(challengeActionProvider.notifier).create(opponentTeamId:int.parse(_opponent.text),gameweek:2,stakeCents:stake);if(ok)_opponent.clear();},child:action.isLoading?const SizedBox.square(dimension:22,child:CircularProgressIndicator(strokeWidth:2)):const Text('Send challenge'))]))),const SizedBox(height:26),Text('Your head-to-heads',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:10),challenges.when(data:(items)=>items.isEmpty?const EmptyState(icon:Icons.compare_arrows_rounded,title:'No challenges yet',message:'Pick a rival and make this gameweek personal.'):Column(children:items.map((item)=>Padding(padding:const EdgeInsets.only(bottom:12),child:_ChallengeCard(item:item))).toList()),loading:()=>const Padding(padding:EdgeInsets.all(32),child:Center(child:CircularProgressIndicator())),error:(error,_)=>Text(error.toString()))])));}}
class _ChallengeCard extends StatelessWidget{const _ChallengeCard({required this.item});final Challenge item;@override Widget build(BuildContext context)=>GradientPanel(child:Row(children:[Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Theme.of(context).colorScheme.secondary.withValues(alpha:.14),borderRadius:BorderRadius.circular(15)),child:Icon(Icons.compare_arrows_rounded,color:Theme.of(context).colorScheme.secondary)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item.opponentName,style:Theme.of(context).textTheme.titleMedium),Text('GW${item.gameweek} · Team ${item.opponentTeamId}',style:Theme.of(context).textTheme.bodySmall?.copyWith(color:Theme.of(context).colorScheme.onSurfaceVariant))])),Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Text(money(item.stakeCents),style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:5),StatusPill(item.status)])]));}
